### Numpy(Numerical Python)

>* 벡터 및 행렬연산에 특화된 라이브러리
* array단위로 데이터를 관리한다. 즉, array단위로 연산을 수행한다.
* 2차원자료구조는 행렬(Matrix)와 유사하다.
* Pandas와 함께 데이타분석에 많이 사용한다.
* 수치해석용 Python 라이브러리

#### 참고사이트
1. home : http://www.numpy.org
2. documentation : http://docs.scipy.org/doc
3. tutrial :
 - http://www.scipy-lectures.org/intro/numpy/index.html
 - http://docs.scipy.org/doc/numpy/user/quickstart.html

In [2]:
# Numpy를 사용하기 위해서는 Numpy모듈을 import해야 한다.
import numpy as np
np.__version__
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

#### 1. 1차원 Array정의 및 사용하기

In [8]:
# 1. np.array() : 데이터를 numpy배열로 리턴
#?np.array
data = [1,2,3,4,5]
print(type(data))

# np.array() : 데이터를 numpy배열 즉, ndarray로 변환해주는 함수
arr = np.array(data)
print(arr)
print(data)
print(type(arr))

# 강제형변환(upcasting)
arr1 = np.array([1,2,3,4.1])
print(arr1)

<class 'list'>
[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1.  2.  3.  4.1]


In [15]:
# 2. np.shape : numpy배열의 크기를 리턴
#?np.shape
a = 4
print(type(a))

b = 4,
print(type(b))

c = (4,)
print(type(c))

print(arr1.shape)
print(np.shape(arr1))
help(arr1.shape)

<class 'int'>
<class 'tuple'>
<class 'tuple'>
(4,)
(4,)
Help on tuple object:

class tuple(object)
 |  tuple(iterable=(), /)
 |  
 |  Built-in immutable sequence.
 |  
 |  If no argument is given, the constructor returns an empty tuple.
 |  If iterable is specified the tuple is initialized from iterable's items.
 |  
 |  If the argument is a tuple, the return value is the same object.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iter__(self, /)
 |      Implement iter(sel

#### 2. 2차원 Array(행렬, Matrix)

In [24]:
# 1. np.array()
# 2차원 리스트
data = [[1,2,3],[4,5,6.0]]
print(type(data))

# 2차원리스트를 2차원 ndarray로 변환
arr = np.array(data)
print(type(arr))
print(arr.shape)
print(arr)

# numpy의 datatype보기
arr.dtype

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1.shape)
print(arr1)

<class 'list'>
<class 'numpy.ndarray'>
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 3. Numpy 연산

##### 1. numpy shape

* numpy에서 해당 array크기를 확인할 수 있는 함수이다. 이 함수는 정수를 리턴한다.
* shape(크기)를 확인 함으로써 numpy배열에 몇개의 데이터가 있는지, 몇차원의 데이터인지를 확인한다.
* 1차원배열일 경우 `(5,)`형태로 2차원 배열일 경우는 `(3,4)`의 형태로 리턴한다>

##### 2. numpy datatype

* int(8,16,32,64) : 부호가 있는 정수 
* uint(8,16,32,64) : 부호가 없는 정수 
* float(16,32,64,126) : 실수
* complex(64,129,256) : 복소수
* bool : boolean
* string : 문자열
* object : 파이썬의 오브젝트(객체)
* unicode : 유니코드

In [31]:
# 1. Numpy배열의 연산
# numpy의 배열은 리스트와 비슷하지만 다듬과 같은 점에서 다르다.
# 1) 모든 원소가 같은 자료형이이어야 한다.
# 2) 원소의 갯수는 바꿀 수가 없다.
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

print("numpy 덧셈:", arr1 + arr2)
print("numpy 뺄셈:", arr1 - arr2)
print("numpy 곱셈:", arr1 * arr2)
print("numpy 나눗셈:", arr1 / arr2)
print("numpy 요소전체 2배:", arr1 * 2)
print("numpy 제곱근:", arr1 ** 2)

numpy 덧셈: [[ 8 10 12]
 [14 16 18]]
numpy 뺄셈: [[-6 -6 -6]
 [-6 -6 -6]]
numpy 곱셈: [[ 7 16 27]
 [40 55 72]]
numpy 나눗셈: [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
numpy 요소전체 2배: [[ 2  4  6]
 [ 8 10 12]]
numpy 제곱슨: [[ 1  4  9]
 [16 25 36]]


In [33]:
# 2. array broadcast
# numpy배열에서는 기본적으로 동일 크기를 가져야 연산이 가능하지만 배열의 크기가 틀릴 경우에
# 이런점을 보완하기 위해 numpy에서는 broadcast라는 기능을 제공해 준다.
# 즉, broadcast는 서로 크기가 다른 numpy배열을 연산이 가능하도록 해주는 기능이다.

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,11,12])        # [[10,11,12], [10,11,12]]

print("numpy 덧셈:", arr1 + arr2)
print("numpy 뺄셈:", arr1 - arr2)
print("numpy 곱셈:", arr1 * arr2)
print("numpy 나눗셈:", arr1 / arr2)
print("numpy 요소전체 2배:", arr1 * 2)
print("numpy 제곱근:", arr1 ** 2)

numpy 덧셈: [[11 13 15]
 [14 16 18]]
numpy 뺄셈: [[-9 -9 -9]
 [-6 -6 -6]]
numpy 곱셈: [[10 22 36]
 [40 55 72]]
numpy 나눗셈: [[0.1        0.18181818 0.25      ]
 [0.4        0.45454545 0.5       ]]
numpy 요소전체 2배: [[ 2  4  6]
 [ 8 10 12]]
numpy 제곱근: [[ 1  4  9]
 [16 25 36]]


#### 4. Numpy Array의 인덱싱과 슬라이싱

* numpy에서 사용되는 인덱싱은 python에서의 인덱싱과 기본적으로 동일하다.
* numpy의 인덱싱은 0부터 시작한다.

In [53]:
# np.arange([start,], stop[, step])
# ?np.arange
arr1 = np.arange(10, 20, 2, dtype='float64')
print(arr1)
print(type(arr1))
print(arr1.dtype)
print() 

# 1차원 array의 인덱싱과 슬라이싱
arr1 = np.arange(10)
print(arr1)
print(arr1[9])
print(arr1[0:3])
print(arr1[:3])
print(arr1[3:])
print(arr1[:-3])
print(arr1[:])

[10. 12. 14. 16. 18.]
<class 'numpy.ndarray'>
float64

[0 1 2 3 4 5 6 7 8 9]
9
[0 1 2]
[0 1 2]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]


In [62]:
# 2차원 array의 인덱싱과 슬라이싱
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print()

# 2차원[행, 요소위치]
print(arr2[0,0])
print(arr2[0,1])
print(arr2[0,2])

print(arr2[1,0])
print(arr2[1,1])
print(arr2[1,2])

print(arr2[2,0])
print(arr2[2,1])
print(arr2[2,2])
print()

# 요소를 꺼내기
# 다차원배열의 원소중 복수개를 접근하려면 slicing과 컴마(,)를 함께 사용하면 된다.
# a[0, :] -> 첫 번째행 전체
# a[:, 1] -> 두 번째열 전체
# a[1, 1:] -> 두 번째 행의 두번째 열부터 끝까지
# a[:2, :2] -> 첫 번째부터 두번쨰행과 첫번쨰열부터 두번째열까지


print(arr2[:])     # 전체요소꺼내기
print(arr2[2:])    # 3번째행(2차원)의 모든 요소 꺼내기
print(arr2[2,:])   # 3번째행(1차원)의 모든 요소 꺼내기

# 9를 꺼내기 : 2행의 3번쨰 요소
# 모든 열의 3번째요소 [3,6,9]
# [[1,2],[4,5]] 꺼내오기
# [[5,6],[8,9]] 꺼내오기

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
2
3
4
5
6
7
8
9

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]]
[7 8 9]


In [197]:
# 실습문제
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

# 이 행렬에서 값 7 을 인덱싱한다.
print(m[1,2])

# 이 행렬에서 값 14 을 인덱싱한다.
print(m[2,4])
print(m[2,-1])
print(m[-1,-1])

# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
print(m[1,1:3])

# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
print(m[1:3, 2:3])

# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
print(m[0:2, 3:5])
print(m[0:2, 3:])

7
14
14
14
[6 7]
[[ 7]
 [12]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


In [75]:
# 배열인덱싱
# numpy배열 객체의 강력한 기능은 팬시 인덱싱(Fancy Indexing)이라고 부르는 배열인덱싱이다. 인덱싱이란 이름이
# 붙었지만 사실은 데이터베이스의 질의(QUery)기능을 수행하다.
# 배열의 인덱싱은 두가지가 있다. 하나는 정수배열방식과 다른 하나는 블리안배열방식이다.
# 블리안 인덱싱 방식은 배열의 원소가 True or False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray
# 객체의 크기와 동일 해야 한다.

a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
print(a)
print(idx)
print(a[idx])

# 짝수만 나오게 할 경우
print(a[a % 2 == 0])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[0 2 4 6 8]


In [80]:
# 2차원 블리안 인덱싱
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

a[:,[True, False, False, True]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [83]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
a = np.array(lst)
print(a)

bool_idx_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])
print(a[bool_idx_array])
print(a[a%2 == 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 4 6 8]
[2 4 6 8]


#### 5. Numpy 함수

##### 1. 한 개의 array적용되는 함수

In [88]:
# 1. zeros() : array가 생성될되 모든 요소의 값을 0으로 초기화하는 함수
?np.zeros
z1 = np.zeros(10)
print(z1)

z2 = np.zeros((10, 5))
print(z2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [91]:
# 2. ones() : array가 생성될되 모든 요소의 값을 1로 초기화하는 함수
# ?np.ones
o1 = np.ones(10)
print(o1)

o2 = np.ones((10,5))
print(o2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [92]:
# 3. arange()
print(np.arange(10, 20, 2, dtype='float32'))

[10. 12. 14. 16. 18.]


In [142]:
# 4. random()
# 1) seed() : seed설정하기
# 특정한 시작 숫자를 정의하지 않으면 실행될 때마다 무작위수가 발생이 된다. 하진 특정의
# 시작 숫자 정해 주면 랜덤 알고리즘은 마치 난수처럼 보이는 수열을 생성한다. 
# 이 시작되는 숫자를 "Seed"라고 한다. 이를 위해 파이썬에서 random모듈을 seed(인수)함수를 
# 제공하는 데 보통 인수는 0 또는 0보다 큰 임의의 수로 설정한다.
# ?np.random.seed

np.random.seed(0)
result = np.random.rand(10)
print(result)

# 2) 난수를 발생 3가지 메서드
# 2-1) rand  : 0~1사이의 균일 분포를 가진 난수 발생
print(np.random.rand(10))
print(np.random.rand(3,5))
print()

# 2-2) randn : 표준정규분포(가우시안)
print(np.random.randn(10))
print(np.random.randn(3,5))
print()

# 3-3) randint : 균일 분포의 정수 난수
# numpy.random.randint(low, high=None, size=None)
# high를 입력하지 않으면 0과 low사이의 숫자를 high를 입력하면 low와 high의 숮자를 생성
# size는 난수의 숫자이다.
print(np.random.randint(10))
print(np.random.randint(10, size=10))
print(np.random.randint(10, 20, size=10))
print(np.random.randint(10, 20, size=(3,5)))
print()

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
[0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
 0.0202184  0.83261985 0.77815675 0.87001215]
[[0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]]

[ 1.46274045  1.53502913  0.56644004  0.14926509 -1.078278    1.39547227
  1.78748405 -0.56951726  0.17538653 -0.46250554]
[[-1.0858006   0.63973599 -0.38586334 -0.77576235  0.99571135]
 [-1.93320478  0.24853063 -0.03124534 -0.13947396 -0.19065598]
 [ 0.44863753 -0.99242977 -0.22593966 -1.65457077 -0.63972264]]

5
[5 0 1 5 9 3 0 5 0 1]
[12 14 12 10 13 12 10 17 15 19]
[[10 12 17 12 19]
 [12 13 13 12 13]
 [14 11 12 19 11]]



In [144]:
# 5. abs()
arr1 = np.random.randn(5,3)
print(arr1)
print(np.abs(arr1))

[[-0.57890879  1.42694855  0.27699691]
 [ 0.78966713  0.32207411  0.70039238]
 [ 0.38871663 -0.04126386  0.29588432]
 [-0.42527999  1.72763912 -0.86835257]
 [-0.82097758 -1.09974201  0.08672983]]
[[0.57890879 1.42694855 0.27699691]
 [0.78966713 0.32207411 0.70039238]
 [0.38871663 0.04126386 0.29588432]
 [0.42527999 1.72763912 0.86835257]
 [0.82097758 1.09974201 0.08672983]]


In [145]:
# 6. square() : 각 요소에 제곱근을 계산
print(np.square(arr1))

[[3.35135383e-01 2.03618217e+00 7.67272854e-02]
 [6.23574177e-01 1.03731735e-01 4.90549482e-01]
 [1.51100620e-01 1.70270620e-03 8.75475315e-02]
 [1.80863068e-01 2.98473693e+00 7.54036191e-01]
 [6.74004183e-01 1.20943249e+00 7.52206323e-03]]


In [146]:
# 7. exp() : 각 요소의 무리수를 e지수로 연산
print(np.exp(arr1))

[[0.56050967 4.16596754 1.31916229]
 [2.2026631  1.37998705 2.01454301]
 [1.4750865  0.9595759  1.34431464]
 [0.65358676 5.62735271 0.41964231]
 [0.44000131 0.33295697 1.09060199]]


In [147]:
# 8. log(), log10(), log2()
# 자연로그, 상용로그, 밑2인 로그
print(np.log(arr1))
print(np.log10(arr1))
print(np.log2(arr1))

[[        nan  0.35553828 -1.28374895]
 [-0.23614378 -1.13297359 -0.35611456]
 [-0.94490465         nan -1.21778671]
 [        nan  0.54675581         nan]
 [        nan         nan -2.44495741]]
[[        nan  0.15440831 -0.55752508]
 [-0.10255594 -0.49204418 -0.15465859]
 [-0.41036688         nan -0.52887805]
 [        nan  0.23745303         nan]
 [        nan         nan -1.06183151]]
[[        nan  0.51293332 -1.85205824]
 [-0.34068345 -1.63453538 -0.51376471]
 [-1.36320926         nan -1.75689484]
 [        nan  0.78880189         nan]
 [        nan         nan -3.52732793]]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log10
  after removing the cwd from sys.path.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log2
  """


In [148]:
# 9. sign() # 각 요소의 값이 음수일 때 -1, 0일 때는 0 양수일 때는 1로 리턴
print(np.sign(arr1))

[[-1.  1.  1.]
 [ 1.  1.  1.]
 [ 1. -1.  1.]
 [-1.  1. -1.]
 [-1. -1.  1.]]


In [149]:
# 10. ceil()
print(np.ceil(arr1))

[[-0.  2.  1.]
 [ 1.  1.  1.]
 [ 1. -0.  1.]
 [-0.  2. -0.]
 [-0. -1.  1.]]


In [150]:
# 11. floor()
print(np.floor(arr1))

[[-1.  1.  0.]
 [ 0.  0.  0.]
 [ 0. -1.  0.]
 [-1.  1. -1.]
 [-1. -2.  0.]]


In [152]:
# 12. isnan() : NaN일 경우는 True, 아닐 경우 False로 리턴
print(np.isnan(arr1))
print(np.isnan(np.log(arr1)))

[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]
[[ True False False]
 [False False False]
 [False  True False]
 [ True False  True]
 [ True  True False]]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


In [153]:
# 13. cos(), sin(), tan(), cosh(), sinh(), tanh()
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

##### 2. 두 개의 array적용되는 함수

In [154]:
arr1 = np.random.randn(5,3)
arr2 = np.random.rand(5,3)
print(arr1)
print(arr2)

[[ 0.45628701  0.4310333   2.07257353]
 [-0.53778512 -1.3784301  -0.49240425]
 [ 2.32773811  1.80440397 -0.24942133]
 [-0.82086383 -1.49333996  0.52417595]
 [ 0.34511317  0.72437468 -2.04038084]]
[[0.03362509 0.96896177 0.32099724]
 [0.22126269 0.1412639  0.09725993]
 [0.98404224 0.26034093 0.53702252]
 [0.44792617 0.09956909 0.35231166]
 [0.46924917 0.84114013 0.90464774]]


In [156]:
# 1. 사칙연산함수(add, subtract, multiply, divide)
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[[ 0.4899121   1.39999507  2.39357078]
 [-0.31652243 -1.23716619 -0.39514432]
 [ 3.31178035  2.06474489  0.2876012 ]
 [-0.37293766 -1.39377087  0.87648761]
 [ 0.81436234  1.56551481 -1.1357331 ]]
[[ 0.42266192 -0.53792846  1.75157629]
 [-0.7590478  -1.519694   -0.58966418]
 [ 1.34369587  1.54406304 -0.78644385]
 [-1.26879    -1.59290905  0.17186428]
 [-0.124136   -0.11676545 -2.94502859]]
[[ 0.01534269  0.41765479  0.66529039]
 [-0.11899178 -0.19472242 -0.0478912 ]
 [ 2.29059263  0.4697602  -0.13394487]
 [-0.36768639 -0.1486905   0.1846733 ]
 [ 0.16194407  0.60930061 -1.84582593]]
[[ 13.56983618   0.44484036   6.45667086]
 [ -2.43052785  -9.75783656  -5.06276598]
 [  2.36548596   6.93092701  -0.46445226]
 [ -1.83258733 -14.99802772   1.48781889]
 [  0.73545824   0.86118193  -2.25544236]]


In [158]:
# 2. 최대값, 최소값(maximum, minimum)
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[[0.45628701 0.96896177 2.07257353]
 [0.22126269 0.1412639  0.09725993]
 [2.32773811 1.80440397 0.53702252]
 [0.44792617 0.09956909 0.52417595]
 [0.46924917 0.84114013 0.90464774]]
[[ 0.03362509  0.4310333   0.32099724]
 [-0.53778512 -1.3784301  -0.49240425]
 [ 0.98404224  0.26034093 -0.24942133]
 [-0.82086383 -1.49333996  0.35231166]
 [ 0.34511317  0.72437468 -2.04038084]]


##### 3. 통계함수

* 통계함수를 통해서 numpy배열의 총합 또는 평균등을 구할 때 유용한 함수들
* 열의 합 또는 행의 합을 쉽게 구할 수 있다.

In [162]:
# 1. sum() : 합계
#?np.sum
print(np.sum(arr1)) # 요소의 전체합
print(np.sum(arr1, axis=0)) # 열의 합
print(np.sum(arr1, axis=1)) # 행의 합

1.6730742988145506
[ 1.77048934  0.0880419  -0.18545694]
[ 2.95989385 -2.40861946  3.88272075 -1.79002784 -0.97089299]


In [165]:
# 2. mean() : 평균
# np.mean?
print(np.mean(arr1)) # 요소 전체 평균
print(np.mean(arr1, axis=0)) # 열의 평균
print(np.mean(arr1, axis=1)) # 행의 평균

0.1115382865876367
[ 0.35409787  0.01760838 -0.03709139]
[ 0.98663128 -0.80287315  1.29424025 -0.59667595 -0.323631  ]


In [169]:
# 3. std()표준편차, var()분산, min()최소값, max()최대값
print(np.std(arr1)) # 요소 전체 표준편차
print(np.std(arr1, axis=0)) # 열의 표준편차
print(np.std(arr1, axis=1)) # 행의 표준편차
print()

print(np.var(arr1)) # 요소 전체 분산
print(np.var(arr1, axis=0)) # 열의 분산
print(np.var(arr1, axis=1)) # 행의 분산
print()

print(np.min(arr1)) # 요소 전체 최소값
print(np.min(arr1, axis=0)) # 열의 최소값
print(np.min(arr1, axis=1)) # 행의 최소값
print()

print(np.max(arr1)) # 요소 전체 최대값
print(np.max(arr1, axis=0)) # 열의 최대값
print(np.max(arr1, axis=1)) # 행의 최대값
print()

1.2558330112559941
[1.10288435 1.2723966  1.34396946]
[0.76794634 0.40740169 1.11224636 0.83876408 1.22375987]

1.577116552160298
[1.21635388 1.61899311 1.80625391]
[0.58974158 0.16597613 1.23709197 0.70352517 1.49758823]

-2.0403808422422274
[-0.82086383 -1.49333996 -2.04038084]
[ 0.4310333  -1.3784301  -0.24942133 -1.49333996 -2.04038084]

2.3277381091718357
[2.32773811 1.80440397 2.07257353]
[ 2.07257353 -0.49240425  2.32773811  0.52417595  0.72437468]



In [171]:
# 4. 위치함수 : argmin()최소값위치, argmax()최대값위치(index)
print(np.argmin(arr1))
print(np.argmax(arr1))

14
6


In [173]:
# 5. 누적함수 : 각 요소의 누적합cumsum(), 누적곱cumprod()
print(np.cumsum(arr1))
print(np.cumprod(arr1))

[0.45628701 0.88732031 2.95989385 2.42210873 1.04367863 0.55127438
 2.87901249 4.68341646 4.43399513 3.6131313  2.11979135 2.64396729
 2.98908046 3.71345514 1.6730743 ]
[ 0.45628701  0.1966749   0.40762319 -0.21921368  0.30217074 -0.14879016
 -0.34634452 -0.62494542  0.15587472 -0.12795192  0.19107571  0.10015729
  0.0345656   0.02503845 -0.05108796]


##### 4. 기타함수

In [182]:
# 1. sort() : 정렬함수
# ?np.sort
arr = np.array([5,4,6,2,3,1])
print(arr)
print(np.sort(arr))
print()

print(np.sort(arr1))  # 행별정렬
print()

print(np.sort(arr1)[0]) # 특정행만 정렬
print(np.sort(arr1)[-2])
print(np.sort(arr1)[:1])
print(np.sort(arr1)[:-1])
print()
 
print(np.sort(arr1, axis=0)) # 행정렬
print(np.sort(arr1, axis=1)) # 열정렬

[5 4 6 2 3 1]
[1 2 3 4 5 6]

[[ 0.4310333   0.45628701  2.07257353]
 [-1.3784301  -0.53778512 -0.49240425]
 [-0.24942133  1.80440397  2.32773811]
 [-1.49333996 -0.82086383  0.52417595]
 [-2.04038084  0.34511317  0.72437468]]

[0.4310333  0.45628701 2.07257353]
[-1.49333996 -0.82086383  0.52417595]
[[0.4310333  0.45628701 2.07257353]]
[[ 0.4310333   0.45628701  2.07257353]
 [-1.3784301  -0.53778512 -0.49240425]
 [-0.24942133  1.80440397  2.32773811]
 [-1.49333996 -0.82086383  0.52417595]]

[[-0.82086383 -1.49333996 -2.04038084]
 [-0.53778512 -1.3784301  -0.49240425]
 [ 0.34511317  0.4310333  -0.24942133]
 [ 0.45628701  0.72437468  0.52417595]
 [ 2.32773811  1.80440397  2.07257353]]
[[ 0.4310333   0.45628701  2.07257353]
 [-1.3784301  -0.53778512 -0.49240425]
 [-0.24942133  1.80440397  2.32773811]
 [-1.49333996 -0.82086383  0.52417595]
 [-2.04038084  0.34511317  0.72437468]]


In [187]:
# 2. unique() : 중복제거함수
# 1) 1차원 중복제거
#?np.unique
names = np.array(['홍길동', '손흥민', '소향', '홍길동', '손흥민'])
print(np.unique(names))

# 2) 2차원 중복제거
values = np.array([[1,2],[1,2],[2,3]])
print(np.unique(values))

# 차원에 대한 요소 갯수가 틀릴 경우 주의
values = np.array([[1,2],[1,2],[2,3,2]])
print(np.unique(values))

['소향' '손흥민' '홍길동']
[1 2 3]
[list([1, 2]) list([2, 3, 2])]


#### 6. 데이터분석실습 - 영화평점데이터

* https://grouplens.org/datasets/movielens
 - older datasets중에서 ml-1m.zip을 다운로드
 - 압축해제를 'd:\yourname\data\movielens 해제
 - 3845라인 : And God Created Woman(...)에서 깨진 문자를 삭제
 - np.loadtxt()

#### 연습문제